// ⚠️ DEMO DATA — Replace with real API queries later
// All exports are clearly marked as mock/demo data

export const DEMO_USER = {
  walletAddress: '0x1A2b3C4d5E6f7A8b9C0d1E2f3A4b5C6d7E8f9A0b',
  displayName: '',
  tier: 'Silver',
  points: 2450,
  pointsToNextTier: 550,
  nextTier: 'Gold',
  tierProgress: 60, // percent
  badgesCount: 7,
  onChainBadges: 2,
  referralsCount: 4,
  referralPointsEarned: 200,
  referralCode: 'CL-0x1A2b',
  rank: 47,
};

export const DEMO_BADGES = [
  {
    id: 'early_adopter',
    name: 'Early Adopter',
    emoji: '🔥',
    earnedAt: 'Jan 15, 2025',
    onChain: true,
    txHash: '0xabc123def456abc123def456abc123def456abc123def456abc123def456abc1',
    locked: false,
    howToEarn: '',
  },
  {
    id: 'power_user',
    name: 'Power User',
    emoji: '⚡',
    earnedAt: 'Feb 3, 2025',
    onChain: true,
    txHash: '0xdef456abc123def456abc123def456abc123def456abc123def456abc123def4',
    locked: false,
    howToEarn: '',
  },
  {
    id: 'first_purchase',
    name: 'First Purchase',
    emoji: '🛒',
    earnedAt: 'Jan 15, 2025',
    onChain: false,
    txHash: null,
    locked: false,
    howToEarn: '',
  },
  {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    emoji: '👥',
    earnedAt: 'Feb 10, 2025',
    onChain: false,
    txHash: null,
    locked: false,
    howToEarn: '',
  },
  {
    id: 'milestone_1000',
    name: 'Milestone: 1000pts',
    emoji: '🎯',
    earnedAt: 'Feb 20, 2025',
    onChain: false,
    txHash: null,
    locked: false,
    howToEarn: '',
  },
  {
    id: 'diamond_hands',
    name: 'Diamond Hands',
    emoji: '💎',
    earnedAt: '',
    onChain: false,
    txHash: null,
    locked: true,
    howToEarn: 'Refer 10 friends',
  },
  {
    id: 'rocket_tier',
    name: 'Rocket Tier',
    emoji: '🚀',
    earnedAt: '',
    onChain: false,
    txHash: null,
    locked: true,
    howToEarn: 'Reach Platinum tier',
  },
  {
    id: 'champion',
    name: 'Champion',
    emoji: '🏆',
    earnedAt: '',
    onChain: false,
    txHash: null,
    locked: true,
    howToEarn: 'Top 10 leaderboard',
  },
];

export const DEMO_ACTIVITY = [
  { id: 1, icon: '🛒', description: 'Purchase reward', source: 'Zara', points: 150, type: 'earn', time: '2h ago' },
  { id: 2, icon: '🏅', description: 'Badge unlocked', source: 'Power User', points: 0, type: 'badge', time: '1d ago' },
  { id: 3, icon: '👥', description: 'Referral bonus', source: 'Friend joined', points: 50, type: 'earn', time: '2d ago' },
  { id: 4, icon: '⚡', description: 'Feature usage', source: 'Dashboard viewed', points: 10, type: 'earn', time: '2d ago' },
  { id: 5, icon: '🎰', description: 'Spin reward', source: 'Lucky spin', points: 200, type: 'earn', time: '3d ago' },
  { id: 6, icon: '🛒', description: 'Purchase reward', source: "McDonald's", points: 80, type: 'earn', time: '4d ago' },
  { id: 7, icon: '🎯', description: 'Milestone reached', source: '1000 pts total', points: 100, type: 'earn', time: '5d ago' },
  { id: 8, icon: '⚡', description: 'Spin used', source: 'Wheel spin', points: -100, type: 'spend', time: '5d ago' },
  { id: 9, icon: '🛒', description: 'Purchase reward', source: 'Nike', points: 120, type: 'earn', time: '6d ago' },
  { id: 10, icon: '👥', description: 'Referral bonus', source: 'Friend joined', points: 50, type: 'earn', time: '7d ago' },
];

export const DEMO_POINTS_HISTORY = [
  { date: 'Feb 20, 2025', event: 'Milestone: 1000pts', amount: 100, balance: 2450, type: 'earn' },
  { date: 'Feb 18, 2025', event: 'Lucky spin', amount: 200, balance: 2350, type: 'earn' },
  { date: 'Feb 18, 2025', event: 'Wheel spin cost', amount: -100, balance: 2150, type: 'spend' },
  { date: 'Feb 15, 2025', event: 'Purchase — Nike', amount: 120, balance: 2250, type: 'earn' },
  { date: 'Feb 10, 2025', event: 'Referral bonus', amount: 50, balance: 2130, type: 'earn' },
  { date: 'Feb 10, 2025', event: 'Social Butterfly badge', amount: 0, balance: 2080, type: 'earn' },
  { date: 'Feb 5, 2025', event: "Purchase — McDonald's", amount: 80, balance: 2080, type: 'earn' },
  { date: 'Feb 3, 2025', event: 'Power User badge', amount: 0, balance: 2000, type: 'earn' },
  { date: 'Jan 20, 2025', event: 'Referral bonus', amount: 50, balance: 2000, type: 'earn' },
  { date: 'Jan 15, 2025', event: 'Purchase — Zara', amount: 150, balance: 1950, type: 'earn' },
  { date: 'Jan 15, 2025', event: 'Early Adopter badge', amount: 0, balance: 1800, type: 'earn' },
  { date: 'Jan 15, 2025', event: 'First Purchase badge', amount: 0, balance: 1800, type: 'earn' },
];

export const DEMO_LEADERBOARD = [
  { rank: 1, wallet: '0xF3a1...9B2c', points: 18420, badges: 12, change: 0 },
  { rank: 2, wallet: '0x7Dc4...1E5f', points: 15890, badges: 9, change: 2 },
  { rank: 3, wallet: '0xA2b8...3F7d', points: 14230, badges: 11, change: -1 },
  { rank: 4, wallet: '0x9E1c...6A4b', points: 12750, badges: 8, change: 1 },
  { rank: 5, wallet: '0x4Bf2...8D3e', points: 11340, badges: 7, change: -2 },
  { rank: 6, wallet: '0xC5d9...2B1a', points: 10980, badges: 6, change: 3 },
  { rank: 7, wallet: '0x1Ea3...7C6f', points: 9870, badges: 5, change: 0 },
  { rank: 8, wallet: '0x8Fb7...4E2d', points: 8650, badges: 8, change: -1 },
  { rank: 9, wallet: '0x3Gc5...9A1b', points: 7430, badges: 4, change: 2 },
  { rank: 10, wallet: '0x6Hd1...5F8c', points: 6920, badges: 6, change: 1 },
  { rank: 11, wallet: '0x2Ie8...3B4a', points: 6210, badges: 3, change: -3 },
  { rank: 12, wallet: '0x5Jf4...7D9e', points: 5890, badges: 5, change: 0 },
  { rank: 13, wallet: '0xB3k2...1G6f', points: 5340, badges: 4, change: 1 },
  { rank: 14, wallet: '0xD7l9...8H2b', points: 4980, badges: 3, change: -1 },
  { rank: 15, wallet: '0xE1m5...4I7c', points: 4560, badges: 2, change: 2 },
  { rank: 16, wallet: '0xF6n3...9J1d', points: 4120, badges: 4, change: 0 },
  { rank: 17, wallet: '0xA9o7...2K5e', points: 3870, badges: 3, change: -2 },
  { rank: 18, wallet: '0xC4p1...6L8f', points: 3540, badges: 2, change: 1 },
  { rank: 19, wallet: '0xB8q6...3M4a', points: 3210, badges: 3, change: 0 },
  { rank: 20, wallet: '0x7Rr2...8N9b', points: 2980, badges: 2, change: -1 },
];

export const DEMO_REFERRALS = [
  { wallet: '0x9Aa1...2Bb3', joined: 'Jan 20, 2025', status: 'Active', earned: 50 },
  { wallet: '0x4Cc5...6Dd7', joined: 'Feb 5, 2025', status: 'Active', earned: 50 },
  { wallet: '0x8Ee9...0Ff1', joined: 'Feb 10, 2025', status: 'Active', earned: 50 },
  { wallet: '0x2Gg3...4Hh5', joined: 'Mar 1, 2025', status: 'Pending', earned: 0 },
];

export const DEMO_REWARDS = [
  {
    id: 'discount_10',
    icon: '🏷️',
    name: '10% Off Next Purchase',
    description: 'Valid at partner stores',
    cost: 500,
  },
  {
    id: 'free_shipping',
    icon: '🚚',
    name: 'Free Shipping',
    description: 'On any order above $20',
    cost: 300,
  },
  {
    id: 'mystery_box',
    icon: '🎁',
    name: 'Mystery Box',
    description: 'Random premium reward',
    cost: 750,
  },
  {
    id: 'early_access',
    icon: '⭐',
    name: 'Early Access',
    description: 'Try features before anyone else',
    cost: 1000,
  },
];

export const SPIN_SEGMENTS = [
  { label: '50 pts', value: 50, color: '#1a3a4a' },
  { label: '100 pts', value: 100, color: '#0a2a3a' },
  { label: '200 pts', value: 200, color: '#003344' },
  { label: 'Rare Badge 🏅', value: 0, color: '#2a1a00', isBadge: true },
  { label: '500 pts', value: 500, color: '#004455' },
  { label: '2x Boost ⚡', value: 0, color: '#1a2a00', isBoost: true },
  { label: '50 pts', value: 50, color: '#1a3a4a' },
  { label: '100 pts', value: 100, color: '#0a2a3a' },
];
